# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_detector.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CapBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CapBtn.setGeometry(QtCore.QRect(20, 190, 131, 71))
        self.CapBtn.setObjectName("CapBtn")
        self.ExtBtn = QtWidgets.QPushButton(self.centralwidget)
        self.ExtBtn.setGeometry(QtCore.QRect(20, 270, 131, 71))
        self.ExtBtn.setObjectName("ExtBtn")
        self.Cam = QtWidgets.QLabel(self.centralwidget)
        self.Cam.setGeometry(QtCore.QRect(170, 20, 611, 471))
        self.Cam.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Cam.setLineWidth(3)
        self.Cam.setText("")
        self.Cam.setObjectName("Cam")
        self.ConfirmCap = QtWidgets.QLabel(self.centralwidget)
        self.ConfirmCap.setGeometry(QtCore.QRect(10, 150, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ConfirmCap.setFont(font)
        self.ConfirmCap.setText("")
        self.ConfirmCap.setAlignment(QtCore.Qt.AlignCenter)
        self.ConfirmCap.setObjectName("ConfirmCap")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.ExtBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Detection"))
        self.CapBtn.setText(_translate("MainWindow", "Capture"))
        self.ExtBtn.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
